@startuml
'''''''''''''''''''''''''''''''''''''''''''''''''

'''''''''''''''''''''''''''''''''''''''''''''''''
title GET /v1/adm-admin-announcement-service/history/inquiry

'''''''''''''''''''''''''''''''''''''''''''''''''
' define diagram participants
'''''''''''''''''''''''''''''''''''''''''''''''''

actor Requestor #80BBEC

box "Admin Panel" #E1FAFD
boundary "adm-admin-announcement-service" as admin_bff #80BBEC
boundary "announcement-service" as announcement_svc #80BBEC

'''''''''''''''''''''''''''''''''''''''''''''''''
' formatting options
'''''''''''''''''''''''''''''''''''''''''''''''''
hide footbox

'autonumber

skinparam defaultFontName Comic Sans MS
skinparam sequence {
ParticipantBorderColor black
ParticipantBackgroundColor #A9DCDF
ParticipantFontName Comic Sans MS
ParticipantFontSize 15
ActorBackgroundColor #A9DCDF
ActorBorderColor black
ArrowFontName Comic Sans MS
}

'''''''''''''''''''''''''''''''''''''''''''''''''
' describe sequence of events
'''''''''''''''''''''''''''''''''''''''''''''''''
==  ==

Requestor ->   admin_bff : GET /v1/adm-admin-announcement-service/history/inquiry
activate admin_bff

group Section: Validate input fields
    note right of admin_bff
        * Validate Mandatory
    end note
      alt If validation is failure/not pass
    note right of admin_bff
      Hard stop.
      Return HTTP Status = "400" and status.code = "8000"
    end note
  Else Else
    note right of admin_bff
      Continue next step
    end note
  end alt
    end group  
group Section: Retrieve announcement
      admin_bff -> announcement_svc : GET /v1/announcement-service/inquiry
      activate announcement_svc
      announcement_svc--> admin_bff  : Response
      deactivate announcement_svc
    alt If (status = "0000")
            note right of admin_bff : Return HTTP Status = "200" and status.code = "0000"
        else Else if (status = "8100")
            note right of admin_bff 
            Hard stop. 
            Return HTTP Status = "404" and status.code = "8100"
            end note 
    else Else
        note right of admin_bff 
        Hard stop. 
        Return HTTP Status = "500" and status.code = "9000
        end note
    end alt   
end group
admin_bff --> Requestor : Response
deactivate admin_bff
@enduml